import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const authors = ['Ricardo Santos Simões', 'João Henrique Rodrigues Castello Girão', 'Gisela Rodrigues da Silva Sasso', 'Rinaldo Florencio da Silva', 'Luís Garcia Alonso', 'Sérgio Ricardo Marques'];
const references = `Bridge EM. Pedagogia médica, 1965, p. 141.\n\nBueno FS. Grande dicionário etimológico prosódico da língua portuguesa. Editora Brasilia, São Paulo, 1974.\n\nCoutinho IL. Pontos de gramática histórica, 1962.\n\nDorland's Illustrated Medical Dictionary. 28th ed., 1994.\n\nFernandes GJM. Eponímia: glossário de termos epônimos em anatomia. Etimologia: dicionário etimológico da nomenclatura natômica. Editora Plêiade, São Paulo, 1999.\n\nGarnier M, Delamare V. Dicionário de termos técnicos de medicina. 2ª ed., 1984.\n\nHouaiss A. Estudos vários sobre palavras, livros, autores, 1979.\n\nPaciornick P. Diconário médico. 2ed. Editora Guanabara Koogan, Rio de Janeiro, 1975.\n\nPepper OHP. Medical etymology. Editora Saunders, Philadelphia, 1949.\n\nPoppelmann C. Dicionário de máximas e expressões em latim. Editora Escala, 2010.\n\nRezende JM. Linguagem Médica. AB Editora e Distribuidora de Livros Ltda, 2000.\n\nSBA. Terminologia anatômica, terminologia anatômica internacional. Editora Manole, São Paulo, 2001.\n\nSilveira S. Lições de português. 1960.\n\nSkinner HA. The origin of medical terms. Baltimore: Williams & Wilkins, 1963.\n\nSousa AT. Ensaio de uma tradução portuguesa da nomina histológica aprovada no IX Congresso internacional de anatomia. Leningrado. Editora Coimbra, Portugal, 1970.`;

export default function AboutPage() {
  return <section className="about-page"><p className="eyebrow">Sobre o projeto</p><h1>Dicionário de etimologia de termos morfológicos</h1><p className="lead">Uma fonte de consulta para facilitar a memorização e o aprendizado da terminologia de Anatomia, Histologia e Embriologia.</p><div className="about-grid"><div><h2>Autores</h2><ul className="author-list">{authors.map((author) => <li key={author}>{author}</li>)}</ul><p className="date">São Paulo, 14 de abril de 2014</p></div><div><h2>Referências bibliográficas</h2><div className="reference-content"><ReactMarkdown remarkPlugins={[remarkGfm]}>{references}</ReactMarkdown></div></div></div><div className="source-note"><h2>Fonte e preservação editorial</h2><p>O conteúdo desta aplicação foi organizado a partir do arquivo <code>dicionario.md</code>. Os textos dos verbetes são exibidos em Markdown e não foram corrigidos ou reescritos, mantendo a forma do material de origem.</p><p>Sites consultados no material: <a href="http://www.dicciomed.es/php/diccio.php">Dicciomed</a>, <a href="http://www.hostdime.com.br/dicionario/mitose.html">Dicionário de mitose</a> e <a href="http://dicciomed.eusal.es/index.php">Dicciomed Eusal</a>.</p></div></section>;
}
